version: '3.1'

services:
  auth:
    build: .
    restart: always
    volumes:
      - node_modules:/usr/src/app/node_modules
    ports:
      - 8081:8081
    command: npm run start:dev
    networks:
      - intern
      - public
    environment:
      NODE_ENV: production
      JWT_SECRET: /run/secrets/json_web_token_secret
    secrets:
      - json_web_token_secret

  db:
    image: mongo:4.0-xenial
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - intern

volumes:
  node_modules:
  mongo_data:

networks:
  intern:
    driver: bridge
    internal: true
  public:
    driver: bridge

secrets:
  json_web_token_secret:
    external: true
