version: '3.1'

services:
  auth:
    build: .
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8081:8081
    # Install nodemon for development env and then run start:dev script
    command: sh -c 'npm install nodemon && npm run start:dev'
    environment:
      NODE_ENV: development
      JWT_SECRET: dev_jwt_secret
