# Long Term Support Node on Alpine
# https://hub.docker.com/_/node/
FROM node:lts

# Environment variables
ENV PORT=8081 NODE_ENV=test

# Expose
EXPOSE 8081

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Bundle app source
COPY . .

CMD [ "npm", "run", "test" ]